query getProductVariant($handle: String!, $selectedOptions: [SelectedOptionInput!]!) {
  product(handle: $handle) {
    variantBySelectedOptions(
    selectedOptions: $selectedOptions
    ) {
      id
    }
  }
}
