query getProductDetails($handle: String!) {
  productByHandle(handle: $handle) {
    title
    productType
    createdAt
    descriptionHtml
    category {
      name
    }
    encodedVariantAvailability
    encodedVariantExistence
    options {
      name
      id
      optionValues {
        name
        id
        swatch {
          image {
            id
            previewImage {
              url
            }
          }
        }
      }
    }
    variants(first: 10) {
      edges {
        node {
          id
          image {
            url
          }
          price {
            amount
            currencyCode
          }
          availableForSale
          selectedOptions {
            name
            value
          }
        }
      }
    }
    images(first: 10) {
      nodes {
        url
        id
      }
    }
    priceRange {
      maxVariantPrice {
        amount
        currencyCode
      }
      minVariantPrice {
        amount
        currencyCode
      }
    }
    compareAtPriceRange {
      maxVariantPrice {
        amount
        currencyCode
      }
      minVariantPrice {
        amount
        currencyCode
      }
    }
  }
}
